name: 'Production Environment'

on:
  push:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    name: 'Live Deployment'
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::806066816337:role/OIDC-Github-Workflow-Config
        role-session-name: OIDC-Github-Workflow-Config
        aws-region: eu-central-1

    - name: Terraform plan
      uses: dflook/terraform-plan@v1
      with:
        path: ./terraform
        label: Production
        backend_config_file: ./terraform/env/prod.tfbackend
        var_file: ./terraform/env/prod.tfvars

    - name: Terraform apply
      uses: dflook/terraform-apply@v1
      with:
        path: ./terraform
        label: Production
        backend_config_file: ./terraform/env/prod.tfbackend
        var_file: ./terraform/env/prod.tfvars
        auto_approve: true
