name: 'Staging Environment'

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    name: 'Staging Resources'
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::806066816337:role/OIDC-Github-Workflow-Config
        role-session-name: OIDC-Github-Workflow-Config
        aws-region: eu-central-1

    - name: Terraform plan
      id: terraform-plan
      uses: dflook/terraform-plan@v1
      with:
        path: ./terraform
        label: Staging
        backend_config_file: ./terraform/env/dev.tfbackend
        var_file: ./terraform/env/dev.tfvars
